version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: mainAdmin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: peanutbot
    volumes:
      - ./data:/var/lib/postgresql/data