ALTER TABLE accounts
DROP COLUMN email,
ADD COLUMN type VARCHAR(255),
ADD COLUMN currencies JSONB,
ADD COLUMN strategy VARCHAR(255),
ADD COLUMN type VARCHAR(255),
ADD COLUMN updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;
